### ISSUE TITLE
whereisOrStart is not safe in presence of asynchronous exceptions

### ISSUE THREAD

**Issue by qnikst** [haskell-distributed/distributed-process-extras#13]
whereisOrStart is not safe  it's not safe if exception is sent to caller then it may die before sending
`()`, so newly registered process will wait forever, and no other processes may be registered, until someone will kill problematic process

**Comment by hyperthunk** [comment]
I don't really use `whereisOrStart`, so I'm happy to drop this, along with Call.hs too.

**Comment by hyperthunk** [comment]
Actually I'm using `Call`, but I'd like to get off it. In order to do that, I need a `whereisRemote` implementation that isn't insanely complicated. Will raise a ticket for that.
